### ISSUE TITLE
userLogin function should be userLogout

### ISSUE THREAD

**Issue by cPanelRyan** [mashhour04/TalentLMS#2]
https://github.com/mashhour04/TalentLMS/blob/066e076cb4a77f82911516cd493355cfb7d36d03/users.js#L146

Looks like a mistake was made and "userLogin" is the name of a function that looks to be intended as the userLogout method..

**Comment by AhmedMashour** [comment]
Thanks @cPanelRyan , I know it's really late reply. the project was left am thinking of revisiting it again, add typescript support and have some unit tests
